kube-prometheus-stack:
  crds:
    enabled: true

  grafana:
    adminPassword: "techflow2025"

    envFromSecret: grafana-oauth

    service:
      type: ClusterIP

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.sayzx.fr
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        - hosts:
            - grafana.sayzx.fr
          secretName: grafana-tls

    persistence:
      enabled: true
      size: 2Gi

    grafana.ini:
      server:
        root_url: https://grafana.sayzx.fr

      auth:
        disable_login_form: false

      auth.generic_oauth:
        enabled: true
        name: Keycloak
        allow_sign_up: true

        client_id: grafana
        client_secret: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}

        scopes: openid profile email

        auth_url: https://keycloak.sayzx.fr/realms/k8s/protocol/openid-connect/auth
        token_url: https://keycloak.sayzx.fr/realms/k8s/protocol/openid-connect/token
        api_url: https://keycloak.sayzx.fr/realms/k8s/protocol/openid-connect/userinfo

        use_pkce: true

        login_attribute_path: preferred_username
        name_attribute_path: name
        email_attribute_path: email

  prometheus:
    service:
      type: ClusterIP
    prometheusSpec:
      retention: 15d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi

  alertmanager:
    enabled: true
    service:
      type: ClusterIP

  nodeExporter:
    enabled: true

  kubeStateMetrics:
    enabled: true

  prometheusOperator:
    tls:
      enabled: false
    admissionWebhooks:
      enabled: true
      patch:
        enabled: true
