apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth
  labels:
    app.kubernetes.io/name: monitoring
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: vdalPvFTCEiOPO4G1h8GcY65CMwSDYTQ
